# Load in NumPy

In [1]:
import numpy as np

# The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[4.0,3.0,5.0],[5.0,6.0,3.0]])
print(b)

[[4. 3. 5.]
 [5. 6. 3.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int32')

In [14]:
# Get Size
a.itemsize

# Get total size
a.nbytes

12

# Accessing/Changing specyfic elements, rows, columns etc

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# Get a specyfic element [row, column]
a[1,5]

13

In [5]:
# Get a specyfic row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
# Get a specyfic column
a[:, 2]

array([ 3, 10])

In [11]:
# startindex : endindex :stepsize
a[0, 1:-1:2]

array([2, 4, 6])

In [14]:
a[1,5] = 20
print(a)

a[:, 2] = 55
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2 55  4  5  6  7]
 [ 8  9 55 11 12 20 14]]


In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# Get specyfic element
b[0,1,1]

4

In [26]:
# Replace
b[:, 1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initialixing Different Types of Arrays

In [27]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# All 1s matrix
np.ones((3,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
# Other number
np.full((2,3), 17)

array([[17, 17, 17],
       [17, 17, 17]])

In [33]:
#Other number (full_like method)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [35]:
# Random decimal number
np.random.rand(4,2)

array([[0.74945259, 0.08939775],
       [0.99100344, 0.19759857],
       [0.56317419, 0.04605442],
       [0.76750619, 0.30159373]])

In [36]:
np.random.random_sample(a.shape)

array([[0.78815548, 0.18340108, 0.57032179, 0.3507034 , 0.51059903,
        0.04721303, 0.7765949 ],
       [0.20817803, 0.1086629 , 0.0783984 , 0.62447069, 0.1085515 ,
        0.50645515, 0.77642166]])

In [40]:
# Random Integer values
np.random.randint(-4,12, size = (5,5))

array([[10,  8,  1,  9,  5],
       [ 0,  2,  8,  0,  3],
       [ 5,  3,  6,  4, -3],
       [10,  6,  1, 11,  7],
       [-3, -3,  7,  8,  5]])

In [42]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [51]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Methematics

In [52]:
a =  np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [53]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

In [55]:
a * 2

array([2, 4, 6, 8])

In [56]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [58]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [59]:
# Take the sin/cos etc
np.sin(a)
np.cos(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Linear Algebra**

In [61]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])