# Load in NumPy

In [1]:
import numpy as np

# The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[4.0,3.0,5.0],[5.0,6.0,3.0]])
print(b)

[[4. 3. 5.]
 [5. 6. 3.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
#Get Shape
b.shape

(2, 3)

In [10]:
#Get Type
a.dtype

dtype('int32')

In [14]:
#Get Size
a.itemsize

#Get total size
a.nbytes

12